public enum OperationName
{
    Unnamed,
    NewProject,
    OpenProject,
    SaveProject,
    SaveProjectAs,
    QuitApp,
    ProjectPropertiesWindow,
    PerspectiveViewWindow,
    PlayerSettingsWindow,
    UpdateCheck,
    LanguageSelection,
    SelectBackgroundImage,
    Undo,
    Redo,
    Cut,
    Copy,
    Paste
}
